from django.db import models


class Window(models.Model):
    # TODO: Refactor this to inherit model from fotutils.models.FotModel, also for Var and Device models
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True,
        help_text="Url friendly title. Leaving it in blank will be autogenerated, but if defined must be unique."
    )
    order = models.SmallIntegerField(null=True, blank=True, default=0)
    active = models.BooleanField(default=True)
    background_img = models.ImageField(upload_to='scenes', blank=True, null=True)
    description = models.CharField(max_length=256, blank=True)

    class Meta:
        ordering = ('order',)

    def __unicode__(self):
        return self.title

    # TODO:
    # def get_absolute_url(self):
    #     return reverse('window_details', args=(self.slug,))
