# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0008_auto_20160316_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='var',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='var',
            order_with_respect_to='device',
        ),
    ]
