# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0009_auto_20160612_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='var',
            name='var_type',
            field=models.CharField(blank=True, choices=[(b'?', b'Bool'), (b'h', b'Short'), (b'H', b'Unsigned Short'), (b'i', b'Integer'), (b'I', b'Unsigned Integer'), (b'f', b'Float'), (b'd', b'Double')], default=b'?', max_length=10, verbose_name=b'Type'),
        ),
    ]
