# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimic',
            name='graphic',
            field=models.TextField(blank=True, help_text=b"Dynamic graphic to represent changes in variables, in case of svg code, tag's attributes could contains variables slug defined in var list, used var in the format `{{ &lt;VAR_SLUG&gt; }}`. If you need to transform a value of a variable define a rule for it."),
        ),
    ]
