# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='operation',
            field=models.TextField(default=b'return value;', help_text=b'JavaScript function content returning the result to assign to the attribute, if the function require params define it in the params field, for multiple sentences be sure to add an `;`', max_length=300),
        ),
        migrations.AlterField(
            model_name='rule',
            name='params',
            field=models.CharField(blank=True, default=b'value', help_text=b'A comma separated list of params to pass to the function with content specified in operation field', max_length=255),
        ),
    ]
