# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimics', '0002_auto_20160429_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mimic',
            options={'ordering': ('x', 'y', 'name')},
        ),
    ]
