# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0008_auto_20160316_1625'),
        ('mimics', '0003_auto_20160429_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimicvar',
            name='graphic',
        ),
        migrations.RemoveField(
            model_name='mimicvar',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='params',
        ),
        migrations.AddField(
            model_name='mimic',
            name='rules',
            field=models.ManyToManyField(blank=True, help_text=b'List of rules to apply in order to change the graphic according variable change', null=True, to='mimics.Rule'),
        ),
        migrations.AddField(
            model_name='rule',
            name='var',
            field=models.ForeignKey(help_text=b'Variable to modify', null=True, on_delete=django.db.models.deletion.CASCADE, to='vars.Var'),
        ),
        migrations.AlterField(
            model_name='mimic',
            name='graphic',
            field=models.TextField(blank=True, help_text=b"Dynamic graphic to represent changes in variables, in case of svg code, tag's attributes could contains variables slug defined in var list. if you need to transform a value of a variable definea rule for it."),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operation',
            field=models.TextField(default=b'return <SOME_VAR_SLUG>;', help_text=b'JavaScript function content returning the result to assign to the attribute. Any var slug can be used as var, since all of them will be passed by parameters, for multiple sentences be sure to add an `;`.', max_length=300),
        ),
    ]
