# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimics', '0003_auto_20160314_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimic',
            name='graphic',
            field=models.TextField(blank=True),
        ),
    ]
