# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0003_auto_20150226_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='window',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to=b'scenes'),
        ),
    ]
