# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('home', models.BooleanField(default=False, help_text='Lowest ordered Item this this field in true will be the homepage')),
                ('position', models.CharField(choices=[('view', 'View'), ('main', 'Main'), ('user', 'User')], default='view', max_length=15)),
                ('text', models.CharField(blank=True, max_length=32)),
                ('icon', models.CharField(blank=True, help_text='Material design icon name', max_length=32)),
                ('link', models.CharField(blank=True, help_text='URl to go on click, for local views use in the form `#/your_view`', max_length=100)),
                ('mode', models.CharField(blank=True, choices=[('icon-text', 'Icon & Text'), ('icon', 'Icon'), ('text', 'Text')], default='icon-text', max_length=10)),
                ('class_name', models.CharField(blank=True, max_length=32)),
                ('style', models.CharField(blank=True, choices=[('', 'None'), ('md-primary', 'Primary'), ('md-raised', 'Raised'), ('md-warn', 'Warn'), ('md-fab', 'Fab'), ('md-mini', 'Mini'), ('md-accent', 'Accent'), ('md-icon-button', 'Icon Button'), ('md-disabled', 'Disabled')], max_length=15)),
                ('target', models.CharField(blank=True, help_text='Use `_blank` to open a new page, usefull for external links', max_length=10)),
            ],
            options={
                'ordering': ('position', 'order'),
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
    ]
