# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:32
from __future__ import unicode_literals

from django.db import migrations


def add_default_menus(apps, schema_editor):
    MenuItem = apps.get_model('fmenus', 'MenuItem')
    # Mimics menu
    MenuItem.objects.create(order=-1, home=True, position='view', text='Mimics', icon='toys', link='#/mimics')
    # History menu
    MenuItem.objects.create(order=-1, home=True, position='view', text='History', icon='history', link='#/history')
    # Config wizard menu
    MenuItem.objects.create(order=-1, home=True, position='user', text='Configure', icon='build', link='#/config/intro')


class Migration(migrations.Migration):
    dependencies = [
        ('fmenus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_menus),
    ]
