# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmenus', '0002_default_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Specify a parent to display a submenu', null=True, on_delete=django.db.models.deletion.CASCADE, to='fmenus.MenuItem'),
        ),
    ]
